version: '3.7'

services:
  rabbit-mq:
    image: rabbitmq:management
    hostname: my-rabbit
    ports: 
      - "${RABBITMQ_FST_PORT}:15672"
      - "${RABBITMQ_SND_PORT}:5672"
    networks:
      - notifications

  couchdb:
    image: couchdb
    ports:
      - "${COUCHDB_PORT}:5984"
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    networks:
      - notifications

  app:
    image: app 
    build: 
      context: .
    depends_on:
      - couchdb
      - rabbit-mq
    environment:
      - COUCHDB_PORT=${COUCHDB_PORT} 
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - COUCHDB_HOST=couchdb
      - COUCHDB_NAME=${COUCHDB_NAME}
      - RABBIT_HOST=rabbit-mq
      - RABBIT_USER=${RABBITMQ_USER}
      - RABBIT_PASSWORD=${RABBITMQ_PASSWORD}
      - BROADCASTING_KEY=${BROADCASTING_KEY}
      - SOCKET_URL=${SOCKET_URL}
    ports: 
      - "${PORT}:4000"
    networks:
      - notifications
networks:
    notifications:
        driver: bridge
        name: notifications